name: mcd_dart
description: Magic Card Detector implemented in Dart.
version: 0.0.1

environment:
  sdk: ^3.7.2

dependency_overrides:
  uuid: ^4.5.1
  image: ^4.5.4

# Add regular dependencies here.
dependencies:
  args: ^2.7.0
  image: ^4.5.4 # Image processing
  path: ^1.9.1 # File path manipulations
  image_compare: ^1.1.2 # Perceptual hashing (used by our custom ImageHash implementation)
  collection: ^1.19.1 # Utility collections
  fast_log: ^1.0.7
  scryfall_api: ^2.2.0 # Used for looking up additional card data

dev_dependencies:
  lints: ^5.1.1
