name: mcd_dart
description: Magic Card Detector implemented in Dart.
version: 0.0.1

environment:
  sdk: ^3.7.2

dependency_overrides:

# Add regular dependencies here.
dependencies:
  args: ^2.7.0
  image: ^4.5.4 # Image processing
  path: ^1.9.1 # File path manipulations
  fast_log: ^1.0.7
  scryfall_api: ^2.2.0 # Used for looking up additional card data
  http: ^1.3.0 # Used for HTTP requests
  interact: ^2.2.0 # CLI interactive interface
  flython: ^0.2.0

dev_dependencies:
  lints: ^5.1.1
